midata = {}
(midata)
user_ ="kevincoder"
password_ = "5921"
leerdata = (midata)
user ="profecode" and "1234"
user ="alfa_3" and "5566"
print("Bienvenidos ingrese sus datos")
print("Usuario: ")
user = input()
print("contraseña")
password = input()
if user==user_ and password==password_:
    print("Bienvenidos al programa!")
else:
    print("usuario o contraseña incorrecta, intentelo de nuevo")
    